# Generated by Django 5.2.11 on 2026-07-27 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lead', '0004_lead_demo_done_date_lead_demo_scheduled_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('flow_type', models.CharField(choices=[('lifecycle', 'Lifecycle Rule (Reactive)'), ('drip', 'Drip Campaign (Nurture)')], default='lifecycle', max_length=20)),
                ('trigger', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal display name', max_length=255)),
                ('meta_template_name', models.CharField(help_text='snake_case meta identifier', max_length=255, unique=True)),
                ('category', models.CharField(choices=[('MARKETING', 'Marketing'), ('UTILITY', 'Utility'), ('AUTHENTICATION', 'Authentication')], default='UTILITY', max_length=20)),
                ('language', models.CharField(default='en_US', max_length=20)),
                ('header_type', models.CharField(choices=[('NONE', 'None'), ('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('DOCUMENT', 'Document')], default='NONE', max_length=15)),
                ('header_text', models.CharField(blank=True, help_text='Required if header_type is TEXT. Max 60 chars.', max_length=60)),
                ('header_media_example_url', models.URLField(blank=True, help_text='Public URL for Meta to review the media header.')),
                ('body', models.TextField(help_text='Message body. Max 1024 chars.')),
                ('body_variable_examples', models.JSONField(default=list, help_text="List of example strings for variables like {{1}}. E.g., ['John', 'Tuesday']")),
                ('meta_id', models.CharField(blank=True, help_text='Template ID returned by Meta', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Meta Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'whatsapp_messagetemplate',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=30)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('delivered_count', models.PositiveIntegerField(default=0)),
                ('read_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('reply_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp.messagetemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppCampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=30)),
                ('whatsapp_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_context', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='whatsapp.whatsappcampaign')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead.lead')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_id', models.CharField(max_length=128, unique=True)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('is_automated', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('unassigned', 'Unassigned'), ('active', 'Active'), ('resolved', 'Resolved')], db_index=True, default='unassigned', max_length=20)),
                ('is_starred', models.BooleanField(db_index=True, default=False)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('unread_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_chats', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_chats', to='lead.lead')),
            ],
        ),
        migrations.CreateModel(
            name='ChatAutomationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.PositiveIntegerField(default=1)),
                ('waiting_for_reply', models.BooleanField(default=False)),
                ('next_execution_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_execution', models.DateTimeField(auto_now=True)),
                ('flow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatsapp.automationflow')),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='whatsapp.whatsappchat')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('sender_type', models.CharField(choices=[('customer', 'Customer'), ('agent', 'Agent'), ('system', 'System')], max_length=20)),
                ('direction', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], max_length=20)),
                ('message_type', models.CharField(max_length=50)),
                ('body', models.TextField(blank=True, null=True)),
                ('media_url', models.TextField(blank=True, null=True)),
                ('template_name', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(default='sent', max_length=20)),
                ('meta_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign_recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='whatsapp.whatsappcampaignrecipient')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp.whatsappchat')),
            ],
        ),
        migrations.CreateModel(
            name='AutomationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('action', models.CharField(max_length=100)),
                ('config', models.JSONField(default=dict)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='whatsapp.automationflow')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('flow', 'order')},
            },
        ),
        migrations.AddIndex(
            model_name='whatsappcampaign',
            index=models.Index(fields=['status', 'created_at'], name='whatsapp_wh_status_19d88c_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappcampaignrecipient',
            index=models.Index(fields=['campaign', 'status', 'id'], name='whatsapp_wh_campaig_e5f62b_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappcampaignrecipient',
            index=models.Index(fields=['lead'], name='whatsapp_wh_lead_id_f183da_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappcampaignrecipient',
            index=models.Index(fields=['whatsapp_message_id'], name='whatsapp_wh_whatsap_5a0b5c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='whatsappcampaignrecipient',
            unique_together={('campaign', 'lead')},
        ),
        migrations.AddIndex(
            model_name='whatsappchat',
            index=models.Index(fields=['lead'], name='whatsapp_wh_lead_id_d71f5c_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappchat',
            index=models.Index(fields=['status', '-last_message_at'], name='whatsapp_wh_status_f9f187_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappchat',
            index=models.Index(fields=['assigned_to', 'status', '-last_message_at'], name='whatsapp_wh_assigne_bc6ba3_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappchat',
            index=models.Index(fields=['is_starred', 'status'], name='whatsapp_wh_is_star_9e618b_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['chat', '-created_at'], name='whatsapp_wh_chat_id_630f4d_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['status'], name='whatsapp_wh_status_55e250_idx'),
        ),
    ]
