# Generated by Django 5.2.7 on 2025-12-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0233_passwordresetotp_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='studentticket',
            name='priority',
            field=models.CharField(default='Low', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentticket',
            name='status',
            field=models.CharField(default='New', max_length=20),
        ),
    ]
