# Generated by Django 5.2.9 on 2025-12-05 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0234_passwordresetotp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='super_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
