# Generated by Django 5.2.9 on 2025-12-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0235_passwordresetotp_and_more'),
    ]

    operations = [

        migrations.CreateModel(
            name='ReleaseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField()),
                ('release_notes', models.FileField(null=True, upload_to='release_notes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
