# Generated by Django 5.2.9 on 2026-01-20 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0237_passwordresetotp_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='certificate',
            name='student',
            field=models.ForeignKey(blank=True, db_column='student_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='aryuapp.student'),
        ),
    ]
