# Generated by Django 5.2.9 on 2026-01-21 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0238_passwordresetotp_and_more'),
        ('webinar', '0008_webinar_registration_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='webinar_registration',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='webinar.webinarregistration'),
        ),
    ]
