# Generated by Django 5.2.9 on 2026-01-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0239_passwordresetotp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='batchcoursetrainer',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='leadcalllog',
            name='notes',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_file',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testquestions',
            name='options',
            field=models.JSONField(blank=True, help_text='MCQ options from frontend', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testquestions',
            name='question',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
