# Generated by Django 5.2.9 on 2026-02-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0240_passwordresetotp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentticket',
            name='ticket_type',
            field=models.CharField(default='support', max_length=30),
        ),
    ]
