# Generated by Django 5.2.11 on 2026-02-27 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0242_alter_certificate_certificate_file'),
        ('webinar', '0026_webinarregistration_webinar_web_registe_3cfe76_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentticket',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentticket',
            name='token_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='studentticket',
            name='token_is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentticket',
            name='webinar_participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webinar.webinarregistration'),
        ),
        migrations.AlterField(
            model_name='studentticket',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='aryuapp.student'),
        ),
    ]
