# Generated by Django 5.2.11 on 2026-02-27 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0243_studentticket_token_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentticket',
            name='token_expires_at',
        ),
        migrations.RemoveField(
            model_name='studentticket',
            name='token_hash',
        ),
        migrations.RemoveField(
            model_name='studentticket',
            name='token_is_used',
        ),
    ]
