# Generated by Django 5.2.11 on 2026-03-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0245_studentticket_email_studentticket_name_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['is_archived', 'status'], name='batch_is_arch_b9d175_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['created_by', 'created_by_type'], name='batch_created_cd2ac8_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['created_at'], name='batch_created_4968ae_idx'),
        ),
        migrations.AddIndex(
            model_name='batchcoursetrainer',
            index=models.Index(fields=['trainer', 'batch'], name='aryuapp_bat_trainer_003b19_idx'),
        ),
        migrations.AddIndex(
            model_name='batchcoursetrainer',
            index=models.Index(fields=['trainer', 'student'], name='aryuapp_bat_trainer_fd19ab_idx'),
        ),
        migrations.AddIndex(
            model_name='batchcoursetrainer',
            index=models.Index(fields=['batch', 'course'], name='aryuapp_bat_batch_i_ca9d5a_idx'),
        ),
    ]
