# Generated by Django 5.2.11 on 2026-03-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0246_batch_batch_is_arch_b9d175_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['student'], name='aryuapp_pay_student_4f5245_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['course'], name='aryuapp_pay_course__5e7692_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['id'], name='aryuapp_pay_id_f5bde4_idx'),
        ),
    ]
