# Generated by Django 5.2.11 on 2026-03-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0247_paymenttransaction_aryuapp_pay_student_4f5245_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='order_id',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='payment_attachments/'),
        ),
        migrations.AddField(
            model_name='settings',
            name='razorpay_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='payment_method',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
