# Generated by Django 5.2.11 on 2026-03-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0248_remove_paymenttransaction_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
