# Generated by Django 5.2.11 on 2026-03-20 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0250_role_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.RemoveField(
            model_name='recurringschedule',
            name='batch',
        ),
    ]
