# Generated by Django 5.2.11 on 2026-03-20 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0252_alter_trainerattendance_batch_and_more'),
        ('batches', '0001_initial'),
        ('courses', '0002_course_aryuapp_cou_course__ba8ce1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='alternate_mobile_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='internship_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_referenced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='reference_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='source_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='aadhar_card',
            field=models.FileField(blank=True, null=True, upload_to='trainers_data/adharcard'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='account_holder_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='account_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='bank_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='trainers_data/certificate'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='trainer_courses', to='courses.course'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='experience',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='gpay_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='last_company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='linkedin_profile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to='trainers_data/pancard'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='trainers_data/photo'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='trainers_data/resume'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='salary',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='salary_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='short_bio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='tutor_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='upi_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='internship',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'date'], name='attendance_student_0943ef_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status'], name='attendance_status_a068a7_idx'),
        ),
    ]
