# Generated by Django 5.2.11 on 2026-03-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0253_student_alternate_mobile_no_student_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
