# Generated by Django 5.2.11 on 2026-03-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0254_alter_trainer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='source_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
