# Generated by Django 5.2.11 on 2026-04-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0255_alter_student_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
