# Generated by Django 5.2.11 on 2026-05-14 11:47

import aryuapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0256_alter_note_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='gst_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='acc_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='cgst_percentage',
            field=models.DecimalField(decimal_places=2, default=9, max_digits=5),
        ),
        migrations.AddField(
            model_name='settings',
            name='email_logo',
            field=models.FileField(blank=True, null=True, upload_to='logos/', validators=[aryuapp.models.validate_image_or_svg]),
        ),
        migrations.AddField(
            model_name='settings',
            name='gst_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='igst_percentage',
            field=models.DecimalField(decimal_places=2, default=18, max_digits=5),
        ),
        migrations.AddField(
            model_name='settings',
            name='sgst_percentage',
            field=models.DecimalField(decimal_places=2, default=9, max_digits=5),
        ),
        migrations.AddField(
            model_name='settings',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='converter',
            field=models.CharField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='source_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_gst_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Login', 'Login'), ('Logout', 'Logout'), ('Breakin', 'Breakin'), ('Breakout', 'Breakout')], max_length=10),
        ),
        migrations.AlterField(
            model_name='settings',
            name='company_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='declaration',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterModelTable(
            name='settings',
            table=None,
        ),
    ]
