# Generated by Django 6.0.4 on 2026-06-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0258_leaddmlog_leadfollowup_leadstatushistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
