# Generated by Django 6.0.4 on 2026-06-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0259_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='date_format',
            field=models.CharField(choices=[('DD-MM-YYYY', 'DD-MM-YYYY'), ('MM-DD-YYYY', 'MM-DD-YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD'), ('DD/MM/YYYY', 'DD/MM/YYYY'), ('DD/MM/YY', 'DD/MM/YY')], default='DD-MM-YYYY', max_length=20),
        ),
        migrations.AddField(
            model_name='settings',
            name='phone_format',
            field=models.CharField(choices=[('INDIA', 'India (+91)'), ('US', 'US (+1)'), ('RAW', 'Raw Number')], default='INDIA', max_length=20),
        ),
        migrations.AddField(
            model_name='settings',
            name='time_format',
            field=models.CharField(choices=[('12', '12 Hours'), ('24', '24 Hours')], default='24', max_length=10),
        ),
    ]
