# Generated by Django 6.0.4 on 2026-06-10 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0260_settings_date_format_settings_phone_format_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lead',
            name='aryuapp_lea_phone_1ca735_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='aryuapp_lea_status_210b70_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='aryuapp_lea_followu_8c4fb9_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='aryuapp_lea_next_fo_5043be_idx',
        ),
        migrations.RemoveField(
            model_name='leadstatushistory',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='leadfollowup',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='leaddmlog',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='leaddmlog',
            name='handled_by',
        ),
        migrations.RemoveField(
            model_name='leadfollowup',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='leadstatushistory',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='followup_by',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='handled_by',
        ),
        migrations.DeleteModel(
            name='LeadCallLog',
        ),
        migrations.DeleteModel(
            name='LeadDMLog',
        ),
        migrations.DeleteModel(
            name='LeadFollowUp',
        ),
        migrations.DeleteModel(
            name='LeadStatusHistory',
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
