# Generated by Django 6.0.4 on 2026-06-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0262_alter_trainer_ifsc_code_studentsubusertype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
