# Generated by Django 6.0.4 on 2026-06-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0263_alter_student_student_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_sub_type',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
