# Generated by Django 6.0.4 on 2026-06-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0264_student_student_sub_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='converter',
            field=models.CharField(),
        ),
    ]
