# Generated by Django 6.0.4 on 2026-07-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0265_alter_student_converter'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionreply',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2026-06-04 04:45:04.668524+00'),
            preserve_default=False,
        ),
    ]
