# Generated by Django 6.0.4 on 2026-07-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0266_submissionreply_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='short_bio',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
