# Generated by Django 6.0.4 on 2026-07-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0267_alter_trainer_short_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='converter',
            field=models.CharField(max_length=100),
        ),
    ]
