# Generated by Django 6.0.4 on 2026-07-14 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0268_alter_student_converter'),
        ('batches', '0004_batchrecording'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_recordings', to='batches.batchrecording')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_recordings', to='aryuapp.student')),
            ],
            options={
                'db_table': 'aryuapp_student_recordings',
                'unique_together': {('student', 'recording')},
            },
        ),
    ]
