# Generated by Django 6.0.4 on 2026-07-14 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0269_studentrecording'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionreply',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission_replies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submissionreply',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='aryuapp.submission'),
        ),
    ]
