# Generated by Django 6.0.4 on 2026-07-16 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0270_submissionreply_user_and_more'),
        ('batches', '0004_batchrecording'),
        ('courses', '0007_topic_scheduled_date_topic_scheduled_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_courses', to='batches.newbatch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_courses', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_courses', to='aryuapp.student')),
            ],
            options={
                'db_table': 'aryuapp_studentcourse',
                'unique_together': {('student', 'course', 'batch')},
            },
        ),
    ]
