# Generated by Django 6.0.4 on 2026-08-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0271_studentcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch_timing',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='information',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
