# Generated by Django 6.0.4 on 2026-08-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0272_student_batch_timing_student_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
