# Generated by Django 5.2.11 on 2026-09-11 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0273_studentcourse_is_paid_studentcourse_status'),
        ('resume', '0009_resumeregistration_auth_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentticket',
            name='resume_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='resume.resumeregistration'),
        ),
        migrations.AddField(
            model_name='ticketreply',
            name='resume_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_replies', to='resume.resumeregistration'),
        ),
    ]
