# Generated by Django 5.2.11 on 2026-03-20 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aryuapp', '0251_delete_announcement_remove_recurringschedule_batch'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=10, null=True)),
                ('total_marks', models.PositiveIntegerField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
            options={
                'db_table': 'aryuapp_test',
            },
        ),
        migrations.CreateModel(
            name='TestQuestions',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(max_length=20)),
                ('options', models.JSONField(blank=True, help_text='MCQ options from frontend', max_length=255, null=True)),
                ('marks', models.PositiveBigIntegerField(blank=True, null=True)),
                ('written_answer', models.TextField(blank=True, help_text='Correct answer for written questions', null=True)),
                ('mcq_correct_option', models.CharField(blank=True, max_length=255, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_questions', to='tests.test')),
            ],
            options={
                'db_table': 'aryuapp_testquestions',
            },
        ),
        migrations.CreateModel(
            name='StudentAnswers',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('selected_option', models.TextField(blank=True, null=True)),
                ('written_answer', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('question_text', models.TextField(blank=True, null=True)),
                ('options_snapshot', models.JSONField(blank=True, null=True)),
                ('correct_answer_snapshot', models.TextField(blank=True, null=True)),
                ('marks_snapshot', models.FloatField(blank=True, null=True)),
                ('student_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='aryuapp.student')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_test_answers', to='tests.test')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='tests.testquestions')),
            ],
            options={
                'db_table': 'aryuapp_studentanswers',
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('time_taken', models.DurationField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(auto_now=True)),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_results', to='aryuapp.trainer')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='aryuapp.student')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='tests.test')),
            ],
            options={
                'db_table': 'aryuapp_testresult',
            },
        ),
    ]
