# Generated by Django 6.0.4 on 2026-04-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymenttransaction_course_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
