# Generated by Django 6.0.4 on 2026-06-04 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0258_leaddmlog_leadfollowup_leadstatushistory_and_more'),
        ('courses', '0003_course_duration_type'),
        ('ebook', '0001_initial'),
        ('payments', '0004_paymenttransaction_amount_received_and_more'),
        ('resume', '0002_alter_subscription_duration_days'),
        ('webinar', '0034_alter_webinarregistration_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='ebookregistration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='ebook.ebookregistration'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='resume_registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='resume.resumeregistration'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='resume.subscription'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['resume_registration'], name='aryuapp_pay_resume__91ca46_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['subscription'], name='aryuapp_pay_subscri_7903e5_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['payment_status'], name='aryuapp_pay_payment_d7abd9_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['created_at'], name='aryuapp_pay_created_0f5bb2_idx'),
        ),
    ]
