# Generated by Django 6.0.4 on 2026-08-12 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0272_student_batch_timing_student_information_and_more'),
        ('batches', '0004_batchrecording'),
        ('courses', '0007_topic_scheduled_date_topic_scheduled_end_time_and_more'),
        ('payments', '0005_paymenttransaction_ebookregistration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_type', models.CharField(choices=[('batch_payment', 'Batch Payment'), ('percentage_from_course_fee', '% from Course Fee')], max_length=50)),
                ('tutor_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('payment_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_payments', to='batches.newbatch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_payments', to='courses.course')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_payments', to='aryuapp.trainer')),
            ],
            options={
                'db_table': 'aryuapp_tutorpayment',
                'indexes': [models.Index(fields=['tutor'], name='aryuapp_tut_tutor_i_ef5cf6_idx'), models.Index(fields=['course'], name='aryuapp_tut_course__0f23ee_idx'), models.Index(fields=['batch'], name='aryuapp_tut_batch_i_963133_idx'), models.Index(fields=['payment_status'], name='aryuapp_tut_payment_9ba325_idx'), models.Index(fields=['payment_date'], name='aryuapp_tut_payment_bacf17_idx')],
            },
        ),
    ]
