# Generated by Django 6.0.4 on 2026-08-25 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0273_studentcourse_is_paid_studentcourse_status'),
        ('courses', '0008_alter_course_course_category'),
        ('payments', '0006_tutorpayment'),
        ('webinar', '0040_webinar_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(default='COMPLETED', max_length=50)),
                ('payment_method', models.CharField(default='GATEWAY', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bootcamp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_reports', to='webinar.webinar')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_reports', to='courses.course')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_reports', to='aryuapp.student')),
            ],
            options={
                'db_table': 'aryuapp_paymentreport',
                'indexes': [models.Index(fields=['transaction_id'], name='aryuapp_pay_transac_c7198e_idx'), models.Index(fields=['student'], name='aryuapp_pay_student_a326a2_idx'), models.Index(fields=['payment_status'], name='aryuapp_pay_payment_bb3641_idx'), models.Index(fields=['created_at'], name='aryuapp_pay_created_5b5d40_idx')],
            },
        ),
    ]
