# Generated by Django 5.2.17 on 2026-09-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_paymentreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorpayment',
            name='payment_type',
            field=models.CharField(max_length=50),
        ),
    ]
