# Generated by Django 5.2.17 on 2026-09-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_tutorpayment_payment_type'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tutorpayment',
            new_name='aryuapp_tut_batch_ed2a8b_idx',
            old_name='aryuapp_tut_batch_i_963133_idx',
        ),
        migrations.AlterField(
            model_name='tutorpayment',
            name='batch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
