# Generated by Django 5.2.9 on 2025-12-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='role',
            field=models.CharField(default='quiz_admin', max_length=50),
        ),
    ]
