# Generated by Django 5.2.9 on 2025-12-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_quiz', '0002_adminuser_is_active_adminuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='admin',
        ),
        migrations.AddField(
            model_name='room',
            name='created_by',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
    ]
