# Generated by Django 5.2.9 on 2025-12-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_quiz', '0003_remove_room_admin_room_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created_by',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='updated_by',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='updated_by',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
    ]
