# Generated by Django 5.2.9 on 2025-12-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_quiz', '0005_adminuser_deleted_at_adminuser_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='mark',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
