# Generated by Django 6.0.4 on 2026-05-28 11:46

import django.db.models.deletion
import ebook.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0004_paymenttransaction_amount_received_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=550)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('sub_title', models.CharField(default=True, max_length=250, null=True)),
                ('key', models.CharField(default=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('regular_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ebook_image', models.FileField(blank=True, null=True, upload_to='ebook_images/')),
                ('description', models.TextField()),
                ('pdf', models.FileField(blank=True, null=True, upload_to='ebook_pdf/')),
                ('is_paid', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('seats_available', models.PositiveIntegerField(default=10)),
                ('created_by', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(default='Tamil', max_length=50)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, help_text='YouTube/Vimeo embed URL', null=True)),
                ('testimonial', models.URLField(blank=True, help_text='YouTube/Vimeo embed URL', null=True)),
                ('popular', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EbookFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_question', models.CharField(max_length=500)),
                ('faq_answer', models.TextField()),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='ebook.ebook')),
            ],
        ),
        migrations.CreateModel(
            name='EbookRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(blank=True, max_length=250, null=True)),
                ('phone', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=ebook.models.ebook_profile_pic_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_registration_open', models.BooleanField(default=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='ebook.ebook')),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ebook_registrations', to='payments.paymenttransaction')),
            ],
        ),
        migrations.CreateModel(
            name='EbookSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(max_length=250)),
                ('seo_description', models.TextField()),
                ('seo_image', models.ImageField(blank=True, null=True, upload_to='seo_images/')),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='ebook.ebook')),
            ],
        ),
        migrations.CreateModel(
            name='EbookTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_title', models.CharField(max_length=250)),
                ('tool_image', models.ImageField(blank=True, null=True, upload_to='tool_images/')),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='ebook.ebook')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('registration', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='ebook.ebookregistration')),
            ],
        ),
    ]
