# Generated by Django 6.0.4 on 2026-08-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='rating',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ebook',
            name='short_description',
            field=models.CharField(blank=True, null=True),
        ),
    ]
