# Generated by Django 6.0.4 on 2026-08-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0002_ebook_rating_ebook_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
