# Generated by Django 5.2.11 on 2026-09-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0003_ebook_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebookregistration',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
