# Generated by Django 5.2.11 on 2026-03-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=100)),
                ('trainer_name', models.CharField(max_length=100)),
                ('rating', models.PositiveIntegerField()),
                ('comments', models.TextField()),
                ('suggestions', models.TextField(blank=True, null=True)),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
    ]
