from django.urls import path
from .views import *
from django.conf.urls.static import static

urlpatterns = [
   path('settings', SettingsViewSet.as_view({'get': 'list', 'post': 'create', 'patch': 'partial_update', 'put': 'update'})),
   path('pics', SettingsPicsViewSet.as_view({'get': 'list'})),
   path('settings/<int:pk>', SettingsViewSet.as_view({'get': 'retrieve', 'patch': 'partial_update', 'put': 'update', 'delete': 'is_archived'})),
   path('cms', CmsViewSet.as_view({'get': 'list', 'post': 'create'})),
   path('cms/<str:link>', CmsViewSet.as_view({'get': 'retrieve'})),
   path("cms/<int:pk>/", CmsViewSet.as_view({'get': 'retrieve', 'patch': 'partial_update', 'put': 'update'})),
   path('cms/<int:pk>/archive', CmsViewSet.as_view({'patch': 'is_archived'})),
   path('login', Login.as_view(), name='login'),
   # path('role',RoleViewSet.as_view('get':'all_view'))
   path('role/<int:pk>',RoleViewSet.as_view({'patch':'status_update'})),
   path('roles', RoleViewSet.as_view({'get': 'list', 'post': 'create'})),
   path('roles/<int:pk>', RoleViewSet.as_view({'get': 'retrieve', 'patch': 'update', 'put': 'update'})),
   path('roles/<int:pk>/archive', RoleViewSet.as_view({'patch': 'is_archived'})),
   path('modules&permissions', ModulePermissionViewSet.as_view({'get': 'list', 'post': 'create'})),
   path('modules&permissions/<int:pk>', ModulePermissionViewSet.as_view({'get': 'retrieve', 'patch': 'update', 'put': 'update'})),
   path('modules&permissions/<int:pk>/archive', ModulePermissionViewSet.as_view({'patch':'is_archived'})),
   path('roles&permissions', RoleModulePermissionViewSet.as_view({'get': 'list', 'post': 'create', 'patch': 'update', 'put': 'update'})),
   path('roles&permissions/<int:pk>', RoleModulePermissionViewSet.as_view({'get': 'retrieve', 'patch': 'update', 'put': 'update'})),
   path('users', UserViewSet.as_view({'get': 'list', 'post': 'create'})),
   path('users/<str:id>', UserViewSet.as_view({'get': 'retrieve', 'patch': 'update', 'put': 'update', 'delete': 'destroy'})),
   path('users/<str:id>/archive', UserViewSet.as_view({'patch': 'archive_user'})),
   path('admins',TrainerViewSet.as_view({'get': 'list_admins'})),
   path('ad_employee/<str:employee_id>', TrainerViewSet.as_view({'get': 'admin_profile'})),
   path('jarugandi/',ReportsViewSet .as_view({'get': 'get_reports'})),
   path('jarugandi', ReportsViewSet.as_view({'get': 'list'})),
   path('student_registration', StudentRegistration.as_view({'get': 'list', 'post': 'create'})),
   path('student_list',StudentListAPIView.as_view({'get': 'get'}), name='student_list'),
   path('attendance', AdminLogViewSet.as_view({'get': 'list'})),
   path('attendance/<int:student_id>', AttendanceViewSet.as_view({'get': 'list', 'post': 'create'})),
   path('attendance/<int:student_id>/adumneoie', AttendanceViewSet.as_view({'post': 'admin_mark_attendance'})),
   path('attendance/<int:student_id>/full_logs', AttendanceViewSet.as_view({'get': 'full_logs'})),
   path('attendance/<int:student_id>/status', AttendanceViewSet.as_view({'get': 'attendance_status'})),
   path('student_profile/<str:student_id>/archive',StudentProfileViewSet.as_view({'patch': 'archive_student'})),
   path('student_profile/<str:student_id>',StudentProfileViewSet.as_view({'get': 'retrieve', 'patch': 'partial_update'})),
   path('student_profile/<str:student_id>/courses',StudentCourseViewSet.as_view({'get': 'list_courses', "post":"assign_course"})),
   path('student_profile/<str:student_id>/courses/edit-course',StudentCourseViewSet.as_view({'patch': "edit_course",'put': "edit_course"})),
   path('student_profile/<str:student_id>/courses/<str:course_id>', StudentCourseViewSet.as_view({'get': 'retrieve_course'})),
   path('student_profile/<str:student_id>/courses/remove/<str:batch_id>/',StudentCourseViewSet.as_view({'delete': 'remove_course'})),
   path('student_profile/<str:student_id>/admin_reset_password', StudentProfileViewSet.as_view({'patch': 'admin_reset_password'})),
   path('forgot-password/', ForgotPasswordView.as_view(), name='forgot-password'),
   path('verify-otp/', VerifyOTPView.as_view(), name='verify-otp'),
   path('reset-password/', ResetPasswordView.as_view(), name='reset-password'),
   path("resend-otp/", ResendOTPView.as_view(), name="resend-otp"),
   path('student_profile/<str:student_id>/reset_password', StudentProfileViewSet.as_view({'patch': 'reset_password'})),
   path("recordings/<str:student_id>", RecordingsView.as_view({'get': 'list', 'post': 'create'})),
   path("recordings/<str:student_id>/<str:recording_id>", RecordingsView.as_view({'get': 'retrieve', 'patch': 'partial_update', 'put': 'update'})),
   path("recordings/<str:student_id>/<str:recording_id>/archive", RecordingsView.as_view({'patch': 'is_archived'})),
   path('invoice', InvoiceCreateView.as_view({'get': 'list', 'post': 'create'})),
   path('invoice/<str:student_id>', InvoiceDetailView.as_view({'get': 'download_pdf'})),
   path('invoice_list', InvoiceListViewSet.as_view({'get': 'list', 'post': 'create'}), name='invoice_list'),
   path('certificate', CertificateViewSet.as_view({'get': 'list', 'post': 'create'})),
   path('certificates/<str:student_id>', CertificateViewSet.as_view({'get': 'student_certificates'})),
   path('trainers', TrainerViewSet.as_view({'get': 'list','post': 'create',})),
   path('tutor-signup',TutorSignupView.as_view()),
   path('trainers/<str:employee_id>', TrainerViewSet.as_view({'get': 'retrieve','patch': 'partial_update','put': 'update','delete': 'destroy',})),
   path('trainer/<str:employee_id>/courses', TrainerViewSet.as_view({'get': 'get_courses_taken'})),
   path('trainer/<str:employee_id>/batches', TrainerViewSet.as_view({'get': 'get_batches'})),
   path('trainer/<str:employee_id>/student_list', TrainerViewSet.as_view({'get': 'student_list'})),
   path('trainer/<str:employee_id>/student_list/<str:student_id>', TrainerViewSet.as_view({'get': 'trainer_student_profile'})),
   path('trainer/<str:employee_id>/courses/<str:course_id>', TrainerViewSet.as_view({'get': 'get_courses'})),
   path('trainer/<str:employee_id>/reset_password', TrainerViewSet.as_view({'patch': 'reset_password'})),
   path('trainers/<str:employee_id>/archive',TrainerViewSet.as_view({'patch': 'archive_trainer'})),
   path('trainer_attendance/<str:employee_id>', TrainerAttendanceViewSet.as_view({'get': 'list', 'post': 'create'})),
   path('trainer_attendance/<str:employee_id>/adumneoie', TrainerAttendanceViewSet.as_view({'post': 'admin_mark_attendance'})),
   path('trainer_attendance/<str:employee_id>/full_logs', TrainerAttendanceViewSet.as_view({'get': 'full_logs'})),
   path('trainer_list', TrainerListAPIView.as_view(), name='trainer_list'),
   path('trainer_expenses/<str:trainer_id>', TrainerTravelExpenseViewSet.as_view({'get': 'list', 'post': 'create'})),
   path('trainer_expenses/<str:trainer_id>/<str:expense_id>', TrainerTravelExpenseViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update',})),
   path('trainer_expenses/<str:trainer_id>/<str:expense_id>/archive', TrainerTravelExpenseViewSet.as_view({'patch': 'is_archived'})),
   path('holidays', PublicHolidaysView.as_view({'get': 'list'}), name='public_holidays'),
   path('trainer_attendance', TrainerAttendanceViewSet.as_view({'get': 'list', 'post': 'create'})),
   path('leave_request', LeaveRequestViewSet.as_view({'get': 'list', 'post': 'create'})),
   path('student-trainer-data', TrainerStudentMappingAPI.as_view()),
   path('dashboard', UserDashboardView.as_view(), name='user-dashboard'),
   path('employer', EmployerViewSet.as_view({'get': 'list', 'post': 'create'}), name='employer'),
   path('employer/<int:pk>', EmployerViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update'}), name='employer-detail'),
   path('employer/<int:pk>/archive', EmployerViewSet.as_view({'patch': 'is_archived'}), name='is_archived'),
   path('employer/<str:company_id>/student_list', EmployerDashboardViewSet.as_view({'get': 'employees'})),
   path('employer/<str:company_id>/attendance', EmployerDashboardViewSet.as_view({'get': 'attendance'})),
   path('subadmin', SubAdminViewSet.as_view({'get': 'list', 'post': 'create'}), name='subadmin'),
   path('subadmin/<int:pk>', SubAdminViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update'}), name='subadmin-detail'),
   path('subadmin/<int:pk>/archive', SubAdminViewSet.as_view({'patch': 'is_archived'}), name='is_archived'),
   path('subadmin/<int:pk>/reset_password', SubAdminViewSet.as_view({'patch': 'reset_password'})),
   path('assignments', AssignmentViewSet.as_view({'get': 'list', 'post': 'create'}), name='assignment-list'),
   path('courses/<str:course_id>/assignments', AssignmentViewSet.as_view({'get': 'list_by_course'}), name='list-by-course'),
   path('assignments/<int:pk>/archive', AssignmentViewSet.as_view({'patch': 'is_archived'}), name='assignment-archive'),
   path('assignments/<int:pk>', AssignmentViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update', }), name='assignment-detail'),
   path('submissions', SubmissionViewSet.as_view({'get': 'list', 'post': 'create'}), name='submission-list'),
   path('submissions/<int:pk>', SubmissionViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update'}), name='submission-detail'),
   path('submissions/<str:registration_id>/<int:pk>/archive', SubmissionViewSet.as_view({'patch': 'is_archived'}), name='submission-archive'),
   path('submissions/<str:registration_id>', SubmissionViewSet.as_view({'get': 'by_student'}), name='submissions-by-student'),
   path('replies', SubmissionReplyViewSet.as_view({'get': 'list', 'post': 'create'}), name='reply-list'),
   path('replies/<int:pk>/archive', SubmissionReplyViewSet.as_view({'patch': 'is_archived'}), name='reply-archive'),
   path('replies/<int:submission_id>', SubmissionReplyViewSet.as_view({'get': 'list', 'post': 'create'}), name='replies-by-submission'),
   path('alllogs', AdminfullLogViewSet.as_view({'get': 'list'})),
   path("tickets/", StudentTicketViewSet.as_view(), name="tickets"),

   ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

