# Generated by Django 6.0.4 on 2026-08-28 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webinar', '0040_webinar_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus', to='webinar.webinar')),
            ],
        ),
        migrations.CreateModel(
            name='BonusFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bonus_pdfs/')),
                ('bonus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='webinar_bonus.bonus')),
            ],
        ),
    ]
