# Generated by Django 6.0.4 on 2026-09-02 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aryuapp', '0273_studentcourse_is_paid_studentcourse_status'),
        ('batches', '0005_batch_course'),
        ('courses', '0009_course_syllabus_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_google_review', models.BooleanField(default=False)),
                ('review_date', models.DateField(blank=True, db_index=True, null=True)),
                ('screenshot', models.FileField(blank=True, null=True, upload_to='google_reviews/screenshots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='google_reviews', to='batches.newbatch')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='google_reviews', to='courses.course')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='google_reviews', to='aryuapp.student')),
            ],
            options={
                'db_table': 'google_reviews',
                'ordering': ['-review_date', '-created_at'],
                'indexes': [models.Index(fields=['review_date', 'course', 'batch'], name='google_revi_review__d1fa92_idx'), models.Index(fields=['student', 'is_google_review'], name='google_revi_student_6a3b7b_idx')],
            },
        ),
    ]
