# Generated by Django 6.0.4 on 2026-09-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0273_studentcourse_is_paid_studentcourse_status'),
        ('batches', '0005_batch_course'),
        ('courses', '0009_course_syllabus_thumbnail'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='googlereview',
            constraint=models.UniqueConstraint(fields=('student', 'course', 'batch'), name='unique_student_course_batch_review'),
        ),
    ]
