# Generated by Django 6.0.4 on 2026-09-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_googlereview_unique_student_course_batch_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlereview',
            name='screenshot_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
