# Generated by Django 6.0.4 on 2026-09-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_googlereview_screenshot_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlereview',
            name='screenshot_url',
        ),
        migrations.AddField(
            model_name='googlereview',
            name='facebook_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='googlereview',
            name='facebook_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='facebook_reviews/'),
        ),
        migrations.AddField(
            model_name='googlereview',
            name='linkedin_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='googlereview',
            name='linkedin_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='linkedin_reviews/'),
        ),
        migrations.AddField(
            model_name='googlereview',
            name='trustpilot_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='googlereview',
            name='trustpilot_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='trustpilot_reviews/'),
        ),
        migrations.AlterField(
            model_name='googlereview',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='google_reviews/'),
        ),
    ]
