# Generated by Django 6.0.4 on 2026-09-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_googlereview_screenshot_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlereview',
            name='facebook_review_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='googlereview',
            name='linkedin_review_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='googlereview',
            name='trustpilot_review_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
