# Generated by Django 6.0.4 on 2026-09-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0273_studentcourse_is_paid_studentcourse_status'),
        ('batches', '0005_batch_course'),
        ('courses', '0009_course_syllabus_thumbnail'),
        ('reports', '0005_googlereview_facebook_review_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googlereview',
            options={'ordering': ['-google_review_date', '-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='googlereview',
            name='google_revi_review__d1fa92_idx',
        ),
        migrations.RenameField(
            model_name='googlereview',
            old_name='review_date',
            new_name='google_review_date',
        ),
        migrations.AddIndex(
            model_name='googlereview',
            index=models.Index(fields=['google_review_date', 'course', 'batch'], name='google_revi_google__8a9bda_idx'),
        ),
    ]
