# Generated by Django 6.0.4 on 2026-09-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0273_studentcourse_is_paid_studentcourse_status'),
        ('batches', '0005_batch_course'),
        ('courses', '0009_course_syllabus_thumbnail'),
        ('reports', '0006_alter_googlereview_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googlereview',
            options={'ordering': ['-review_date', '-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='googlereview',
            name='google_revi_google__8a9bda_idx',
        ),
        migrations.RenameField(
            model_name='googlereview',
            old_name='google_review_date',
            new_name='review_date',
        ),
        migrations.AddField(
            model_name='googlereview',
            name='is_youtube_testimonial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='googlereview',
            name='youtube_testimonial_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='googlereview',
            name='youtube_testimonial_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name='googlereview',
            index=models.Index(fields=['review_date', 'course', 'batch'], name='google_revi_review__d1fa92_idx'),
        ),
    ]
