# Generated by Django 5.2.11 on 2026-03-20 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aryuapp', '0251_delete_announcement_remove_recurringschedule_batch'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_name', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('scheduled_date', models.DateField()),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'batch',
                'indexes': [models.Index(fields=['is_archived', 'status'], name='batch_is_arch_b9d175_idx'), models.Index(fields=['created_by', 'created_by_type'], name='batch_created_cd2ac8_idx'), models.Index(fields=['created_at'], name='batch_created_4968ae_idx')],
            },
        ),
        migrations.CreateModel(
            name='NewBatch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slots', models.PositiveIntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_batches', to='courses.course')),
                ('students', models.ManyToManyField(blank=True, related_name='new_batches', to='aryuapp.student')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_batches', to='aryuapp.trainer')),
            ],
            options={
                'db_table': 'aryuapp_newbatch',
            },
        ),
        migrations.CreateModel(
            name='BatchCourseTrainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batchcoursetrainer', to='batches.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='aryuapp.student')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aryuapp.trainer')),
            ],
            options={
                'db_table': 'aryuapp_batchcoursetrainer',
                'indexes': [models.Index(fields=['trainer', 'batch'], name='aryuapp_bat_trainer_003b19_idx'), models.Index(fields=['trainer', 'student'], name='aryuapp_bat_trainer_fd19ab_idx'), models.Index(fields=['batch', 'course'], name='aryuapp_bat_batch_i_ca9d5a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration', models.DurationField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_online_class', models.BooleanField(default=False)),
                ('is_class_cancelled', models.BooleanField(default=False)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('meeting_link', models.URLField(blank=True, max_length=500, null=True)),
                ('class_link', models.TextField(blank=True, max_length=500, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='batches.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aryuapp.trainer')),
                ('new_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='batches.newbatch')),
            ],
            options={
                'db_table': 'aryuapp_classschedule',
                'indexes': [models.Index(fields=['trainer'], name='aryuapp_cla_trainer_8664bb_idx'), models.Index(fields=['course'], name='aryuapp_cla_course__101ae3_idx'), models.Index(fields=['created_by'], name='aryuapp_cla_created_6f9b50_idx'), models.Index(fields=['created_by_type'], name='aryuapp_cla_created_7f40da_idx'), models.Index(fields=['scheduled_date'], name='aryuapp_cla_schedul_55d952_idx'), models.Index(fields=['batch'], name='aryuapp_cla_batch_i_3004b8_idx'), models.Index(fields=['new_batch'], name='aryuapp_cla_new_bat_247233_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecurringSchedule',
            fields=[
                ('recurring_id', models.AutoField(primary_key=True, serialize=False)),
                ('recurrence_type', models.CharField(blank=True, max_length=20, null=True)),
                ('days_of_week', models.JSONField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_online_class', models.BooleanField(default=False)),
                ('class_link', models.TextField(blank=True, max_length=500, null=True)),
                ('country', models.CharField(default='IN', max_length=5)),
                ('subdiv', models.CharField(blank=True, max_length=10, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='batches.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('new_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_schedules', to='batches.newbatch')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aryuapp.trainer')),
            ],
            options={
                'db_table': 'aryuapp_recurringschedule',
                'indexes': [models.Index(fields=['new_batch'], name='aryuapp_rec_new_bat_9fb1f5_idx')],
            },
        ),
    ]
