# Generated by Django 5.2.11 on 2026-03-20 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0253_student_alternate_mobile_no_student_discount_and_more'),
        ('batches', '0001_initial'),
        ('courses', '0002_course_aryuapp_cou_course__ba8ce1_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newbatch',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_batches', to='aryuapp.trainer'),
        ),
        migrations.AddIndex(
            model_name='classschedule',
            index=models.Index(fields=['is_archived'], name='aryuapp_cla_is_arch_651ef3_idx'),
        ),
        migrations.AddIndex(
            model_name='newbatch',
            index=models.Index(fields=['batch_id'], name='aryuapp_new_batch_i_45d8f3_idx'),
        ),
    ]
