# Generated by Django 6.0.4 on 2026-06-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0265_alter_student_converter'),
        ('batches', '0002_alter_newbatch_trainer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newbatch',
            name='trainer',
        ),
        migrations.AddField(
            model_name='newbatch',
            name='trainers',
            field=models.ManyToManyField(blank=True, related_name='new_batches', to='aryuapp.trainer'),
        ),
    ]
