# Generated by Django 6.0.4 on 2026-07-14 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0003_remove_newbatch_trainer_newbatch_trainers'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchRecording',
            fields=[
                ('recording_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='batches.newbatch')),
            ],
            options={
                'db_table': 'aryuapp_batch_recordings',
            },
        ),
    ]
