# Generated by Django 6.0.4 on 2026-08-19 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0004_batchrecording'),
        ('courses', '0007_topic_scheduled_date_topic_scheduled_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='course',
            field=models.ForeignKey(default='10', on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='courses.course'),
            preserve_default=False,
        ),
    ]
