# Generated by Django 5.2.11 on 2026-03-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('content_pic', models.ImageField(blank=True, null=True, upload_to='announcements/')),
                ('background_pic', models.ImageField(blank=True, null=True, upload_to='announcements/')),
                ('audience', models.CharField(default='all', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'aryuapp_announcement',
                'ordering': ['-created_at'],
            },
        ),
    ]
