# Generated by Django 6.0.4 on 2026-05-20 12:35

import resources.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='resources/', validators=[resources.models.validate_image_size])),
                ('file', models.FileField(upload_to='resources/', validators=[resources.models.validate_file])),
                ('status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
