# Generated by Django 6.0.4 on 2026-05-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='form',
            field=models.BooleanField(default=False),
        ),
    ]
