# Generated by Django 6.0.4 on 2026-07-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='slug',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
