# Generated by Django 6.0.8 on 2026-09-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_alter_resources_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube/Vimeo embed URL', null=True),
        ),
    ]
