# Generated by Django 5.2.11 on 2026-08-27 07:21

import code_assessment.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aryuapp', '0273_studentcourse_is_paid_studentcourse_status'),
        ('courses', '0008_alter_course_course_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Assessment time limit in minutes (0 means untimed / practice)')),
                ('passing_percentage', models.DecimalField(decimal_places=2, default=60.0, help_text='Minimum score percentage required to pass', max_digits=5)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, help_text='Associated course for this assessment (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coding_assessments', to='courses.course')),
            ],
            options={
                'db_table': 'code_assessment_assessment',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_passed', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(help_text='Direct relationship to existing Student model in aryuapp', on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to='aryuapp.student')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='code_assessment.codingassessment')),
            ],
            options={
                'db_table': 'code_assessment_assessment_attempt',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CodingProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(help_text='Problem statement in Markdown')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, default='easy', max_length=20)),
                ('constraints', models.TextField(blank=True, default='', help_text='Problem constraints (e.g. 1 <= N <= 10^5)')),
                ('input_format', models.TextField(blank=True, default='', help_text='Explanation of input format')),
                ('output_format', models.TextField(blank=True, default='', help_text='Explanation of output format')),
                ('sample_explanation', models.TextField(blank=True, default='', help_text='Explanation of sample cases')),
                ('time_limit_ms', models.PositiveIntegerField(default=2000, help_text='Maximum CPU time allowed per test case in milliseconds', validators=[code_assessment.validators.validate_time_limit])),
                ('memory_limit_mb', models.PositiveIntegerField(default=128, help_text='Maximum RAM allowed per test case in megabytes', validators=[code_assessment.validators.validate_memory_limit])),
                ('supported_languages', models.JSONField(default=list, help_text="Allowed programming language codes, e.g. ['python', 'javascript', 'java', 'cpp']")),
                ('starter_code', models.JSONField(blank=True, default=dict, help_text="Starter code templates keyed by language, e.g. {'python': '...', 'java': '...'}")),
                ('tags', models.JSONField(blank=True, default=list, help_text="Category/topic tags, e.g. ['array', 'string', 'recursion']")),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('total_submissions_count', models.PositiveIntegerField(default=0)),
                ('accepted_submissions_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses', models.ManyToManyField(blank=True, help_text='Associated courses for which this problem is relevant', related_name='coding_problems', to='courses.course')),
            ],
            options={
                'db_table': 'code_assessment_problem',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CodeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('python', 'Python 3'), ('javascript', 'JavaScript (Node.js)'), ('java', 'Java (OpenJDK)'), ('cpp', 'C++ (GCC)'), ('c', 'C (GCC)')], max_length=30)),
                ('source_code', models.TextField(validators=[code_assessment.validators.validate_source_code_size])),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('accepted', 'Accepted'), ('wrong_answer', 'Wrong Answer'), ('compile_error', 'Compile Error'), ('runtime_error', 'Runtime Error'), ('time_limit_exceeded', 'Time Limit Exceeded'), ('memory_limit_exceeded', 'Memory Limit Exceeded'), ('output_limit_exceeded', 'Output Limit Exceeded'), ('system_error', 'System Error'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=30)),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_test_cases', models.PositiveIntegerField(default=0)),
                ('passed_test_cases', models.PositiveIntegerField(default=0)),
                ('execution_time_ms', models.PositiveIntegerField(default=0, help_text='Peak runtime in ms')),
                ('memory_used_kb', models.PositiveIntegerField(default=0, help_text='Peak memory in KB')),
                ('error_message', models.TextField(blank=True, default='', help_text='Sanitized execution error summary')),
                ('compile_output', models.TextField(blank=True, default='', help_text='Sanitized compiler diagnostic output')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(help_text='Direct relationship to existing Student model in aryuapp', on_delete=django.db.models.deletion.CASCADE, related_name='code_submissions', to='aryuapp.student')),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='code_assessment.codingassessment')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='code_assessment.codingproblem')),
            ],
            options={
                'db_table': 'code_assessment_submission',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=100)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_problems', to='code_assessment.codingassessment')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_associations', to='code_assessment.codingproblem')),
            ],
            options={
                'db_table': 'code_assessment_assessment_problem',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CodingTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(blank=True, default='', help_text='Standard input passed to the program via stdin', validators=[code_assessment.validators.validate_stdin_size])),
                ('expected_output', models.TextField(blank=True, default='', help_text='Expected standard output produced by the program on stdout')),
                ('is_sample', models.BooleanField(db_index=True, default=False, help_text='If True, visible as a sample test case in problem description and test runner')),
                ('is_hidden', models.BooleanField(db_index=True, default=True, help_text='If True, hidden from students and used solely for submission scoring')),
                ('explanation', models.TextField(blank=True, default='', help_text='Optional explanation displayed for sample test cases')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='code_assessment.codingproblem')),
            ],
            options={
                'db_table': 'code_assessment_testcase',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionTestCaseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('accepted', 'Accepted'), ('wrong_answer', 'Wrong Answer'), ('time_limit_exceeded', 'Time Limit Exceeded'), ('memory_limit_exceeded', 'Memory Limit Exceeded'), ('runtime_error', 'Runtime Error'), ('system_error', 'System Error')], default='queued', max_length=30)),
                ('execution_time_ms', models.PositiveIntegerField(default=0)),
                ('memory_used_kb', models.PositiveIntegerField(default=0)),
                ('stdout', models.TextField(blank=True, default='')),
                ('stderr', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_case_results', to='code_assessment.codesubmission')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_results', to='code_assessment.codingtestcase')),
            ],
            options={
                'db_table': 'code_assessment_submission_testcase_result',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='codingassessment',
            index=models.Index(fields=['slug'], name='code_assess_slug_e69a8a_idx'),
        ),
        migrations.AddIndex(
            model_name='codingassessment',
            index=models.Index(fields=['course', 'is_active'], name='code_assess_course__853506_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentattempt',
            index=models.Index(fields=['student', 'assessment'], name='code_assess_student_653e32_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentattempt',
            unique_together={('student', 'assessment')},
        ),
        migrations.AddIndex(
            model_name='codingproblem',
            index=models.Index(fields=['slug'], name='code_assess_slug_cef901_idx'),
        ),
        migrations.AddIndex(
            model_name='codingproblem',
            index=models.Index(fields=['difficulty', 'is_active'], name='code_assess_difficu_9e01a7_idx'),
        ),
        migrations.AddIndex(
            model_name='codingproblem',
            index=models.Index(fields=['created_at'], name='code_assess_created_0fabc4_idx'),
        ),
        migrations.AddIndex(
            model_name='codesubmission',
            index=models.Index(fields=['student', 'submitted_at'], name='code_assess_student_5ee4de_idx'),
        ),
        migrations.AddIndex(
            model_name='codesubmission',
            index=models.Index(fields=['problem', 'status'], name='code_assess_problem_f3ed11_idx'),
        ),
        migrations.AddIndex(
            model_name='codesubmission',
            index=models.Index(fields=['assessment', 'student'], name='code_assess_assessm_437f40_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentproblem',
            unique_together={('assessment', 'problem')},
        ),
        migrations.AddIndex(
            model_name='codingtestcase',
            index=models.Index(fields=['problem', 'is_sample'], name='code_assess_problem_9371d2_idx'),
        ),
        migrations.AddIndex(
            model_name='codingtestcase',
            index=models.Index(fields=['problem', 'is_hidden'], name='code_assess_problem_570e6f_idx'),
        ),
        migrations.AddIndex(
            model_name='submissiontestcaseresult',
            index=models.Index(fields=['submission', 'status'], name='code_assess_submiss_5bf84e_idx'),
        ),
    ]
