# Generated by Django 5.2.11 on 2026-06-09 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('alternate_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('qualification', models.CharField(blank=True, max_length=150, null=True)),
                ('user_type', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('course', models.CharField(blank=True, max_length=200, null=True)),
                ('course_interested_in', models.CharField(blank=True, max_length=255, null=True)),
                ('interested', models.BooleanField(default=True)),
                ('reason_to_join', models.TextField(blank=True, null=True)),
                ('reason_not_joining', models.TextField(blank=True, null=True)),
                ('fee_discussed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_join_month', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(blank=True, max_length=150, null=True)),
                ('source_campaign', models.CharField(blank=True, max_length=255, null=True)),
                ('source_platform', models.CharField(blank=True, max_length=100, null=True)),
                ('source_type', models.CharField(blank=True, max_length=100, null=True)),
                ('followup_date', models.DateField(blank=True, null=True)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('no_of_dms', models.PositiveIntegerField(default=0)),
                ('no_of_calls', models.PositiveIntegerField(default=0)),
                ('no_of_followups', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(db_index=True, default='new', max_length=50)),
                ('lead_stage', models.CharField(blank=True, max_length=50, null=True)),
                ('priority', models.CharField(blank=True, max_length=20, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('is_converted', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by_type', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('followup_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'aryuapp_lead',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(blank=True, max_length=50, null=True)),
                ('call_time', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('call_status', models.CharField(blank=True, max_length=50, null=True)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('recording_url', models.FileField(blank=True, null=True, upload_to='call-recordings/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('called_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='lead.lead')),
            ],
            options={
                'db_table': 'aryuapp_leadcalllog',
                'ordering': ['-call_time'],
            },
        ),
        migrations.CreateModel(
            name='LeadDMLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('message_direction', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dm_logs', to='lead.lead')),
            ],
            options={
                'db_table': 'aryuapp_leaddmlog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_date', models.DateField()),
                ('followup_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='lead.lead')),
            ],
            options={
                'db_table': 'aryuapp_leadfollowup',
                'ordering': ['followup_date'],
            },
        ),
        migrations.CreateModel(
            name='LeadStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=50, null=True)),
                ('new_status', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='lead.lead')),
            ],
            options={
                'db_table': 'aryuapp_leadstatushistory',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['phone'], name='aryuapp_lea_phone_1ca735_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='aryuapp_lea_status_210b70_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['followup_date'], name='aryuapp_lea_followu_8c4fb9_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['next_followup_date'], name='aryuapp_lea_next_fo_5043be_idx'),
        ),
    ]
