# Generated by Django 5.2.11 on 2026-06-16 06:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_lead_aryuapp_lea_email_948e71_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='lead',
            new_name='lead_phone_idx',
            old_name='aryuapp_lea_phone_1ca735_idx',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='lead_email_idx',
            old_name='aryuapp_lea_email_948e71_idx',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='lead_status_idx',
            old_name='aryuapp_lea_status_210b70_idx',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='lead_source_idx',
            old_name='aryuapp_lea_source_8efb2d_idx',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='lead_created_idx',
            old_name='aryuapp_lea_created_d1fdab_idx',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='lead_followup_idx',
            old_name='aryuapp_lea_followu_8c4fb9_idx',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='lead_next_followup_idx',
            old_name='aryuapp_lea_next_fo_5043be_idx',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='lead_status_created_idx',
            old_name='aryuapp_lea_status_dcdbf2_idx',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='lead_source_created_idx',
            old_name='aryuapp_lea_source_f4970a_idx',
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(db_index=True, default='fresh', max_length=50),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['is_archived', '-created_at'], name='lead_archive_created_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['is_archived', 'phone'], name='lead_archive_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['is_archived', 'email'], name='lead_archive_email_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['is_archived', 'name'], name='lead_archive_name_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['is_archived', 'status', '-created_at'], name='lead_archive_status_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['is_archived', 'source', '-created_at'], name='lead_archive_source_idx'),
        ),
    ]
