# Generated by Django 5.2.11 on 2026-07-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_rename_aryuapp_lea_phone_1ca735_idx_lead_phone_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='demo_done_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='demo_scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='facebook_campaign',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='profession',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
