# Generated by Django 5.2.9 on 2026-01-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='created_by_type',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='webinar',
            name='created_by',
            field=models.CharField(max_length=50),
        ),
    ]
