# Generated by Django 5.2.9 on 2026-01-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0003_webinar_uuid_webinarregistration_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarregistration',
            name='wants_reminder',
            field=models.BooleanField(default=False),
        ),
    ]
