# Generated by Django 5.2.9 on 2026-01-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0004_webinarregistration_wants_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarregistration',
            name='attended',
            field=models.BooleanField(default=False),
        ),
    ]
