# Generated by Django 5.2.9 on 2026-01-14 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0005_webinarregistration_attended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webinar',
            name='scheduled_end',
        ),
    ]
