# Generated by Django 5.2.9 on 2026-01-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0006_remove_webinar_scheduled_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
