# Generated by Django 5.2.9 on 2026-01-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0007_webinar_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='registration_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
