# Generated by Django 5.2.9 on 2026-01-27 05:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0008_webinar_registration_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='zoom_join_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webinar',
            name='zoom_meeting_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='webinarsession',
            name='zoom_meeting_id',
            field=models.CharField(default=281020, help_text='Zoom meeting ID used for attendance sync', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='WebinarAttendanceLog',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('join_time', models.DateTimeField()),
                ('leave_time', models.DateTimeField()),
                ('duration_seconds', models.PositiveIntegerField()),
                ('source', models.CharField(default='zoom', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='webinar.webinarregistration')),
            ],
            options={
                'ordering': ['join_time'],
            },
        ),
        migrations.CreateModel(
            name='WebinarAttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_duration_seconds', models.PositiveIntegerField(default=0)),
                ('join_count', models.PositiveIntegerField(default=0)),
                ('first_join_at', models.DateTimeField(blank=True, null=True)),
                ('last_leave_at', models.DateTimeField(blank=True, null=True)),
                ('eligible_for_certificate', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summary', to='webinar.webinarregistration')),
            ],
        ),
    ]
