# Generated by Django 5.2.9 on 2026-01-29 11:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0009_webinar_zoom_join_url_webinar_zoom_meeting_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebinarFeedback',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_rating', models.PositiveSmallIntegerField()),
                ('content_quality', models.PositiveSmallIntegerField()),
                ('speaker_quality', models.PositiveSmallIntegerField()),
                ('pace_of_session', models.PositiveSmallIntegerField()),
                ('interaction_rating', models.PositiveSmallIntegerField()),
                ('learned_something_new', models.BooleanField(default=False)),
                ('would_recommend', models.BooleanField(default=False)),
                ('liked_most', models.TextField(blank=True, null=True)),
                ('improvement_suggestions', models.TextField(blank=True, null=True)),
                ('additional_comments', models.TextField(blank=True, null=True)),
                ('interested_in_future_webinars', models.BooleanField(default=False)),
                ('interested_in_paid_courses', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('registration', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='webinar.webinarregistration')),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='webinar.webinar')),
            ],
            options={
                'db_table': 'webinar_feedback',
                'unique_together': {('webinar', 'registration')},
            },
        ),
    ]
