# Generated by Django 5.2.9 on 2026-01-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0010_webinarfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarfeedback',
            name='rating_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='webinar_feedback_ratings/'),
        ),
    ]
