# Generated by Django 5.2.9 on 2026-01-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0011_webinarfeedback_rating_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='language',
            field=models.CharField(default='Tamil', max_length=50),
        ),
        migrations.AddField(
            model_name='webinar',
            name='mentor',
            field=models.CharField(default='Arun', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webinar',
            name='webinar_image',
            field=models.ImageField(blank=True, null=True, upload_to='webinar_images/'),
        ),
    ]
