# Generated by Django 5.2.9 on 2026-01-31 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0012_webinar_language_webinar_mentor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarfeedback',
            name='phone',
            field=models.CharField(default='9677377316', max_length=15),
            preserve_default=False,
        ),
    ]
