# Generated by Django 5.2.9 on 2026-01-31 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0013_webinarfeedback_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='regular_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='webinar',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='webinar',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webinar',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube/Vimeo embed URL', null=True),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='webinar_metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(max_length=100)),
                ('meta_description', models.TextField()),
                ('meta_image', models.ImageField(upload_to='webinar_meta_images/')),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='webinar.webinar')),
            ],
        ),
        migrations.CreateModel(
            name='WebinarTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tools_title', models.CharField(max_length=100)),
                ('tools_image', models.ImageField(upload_to='tool_images/')),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='webinar.webinar')),
            ],
        ),
    ]
