# Generated by Django 5.2.9 on 2026-02-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0014_webinar_regular_price_webinar_slug_webinar_sub_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='slug',
            field=models.SlugField(default='aryu-academy', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
