# Generated by Django 5.2.9 on 2026-02-03 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0015_alter_webinar_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webinar_FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='webinar.webinar')),
            ],
        ),
    ]
