# Generated by Django 5.2.9 on 2026-02-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0016_webinar_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='mode',
            field=models.BooleanField(default=True, help_text='True for online, False for offline'),
        ),
    ]
