# Generated by Django 5.2.9 on 2026-02-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0017_webinar_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar_faq',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webinar_metadata',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webinartool',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
