# Generated by Django 5.2.9 on 2026-02-06 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0018_webinar_faq_is_deleted_webinar_metadata_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='webinar_status',
            field=models.BooleanField(default=True, help_text='True for active, False for inactive'),
        ),
    ]
