# Generated by Django 5.2.9 on 2026-02-13 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0019_webinar_webinar_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarfeedback',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
