# Generated by Django 5.2.9 on 2026-02-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0020_webinarfeedback_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='waba_link',
            field=models.URLField(blank=True, help_text='whatsapp redirect url', null=True),
        ),
    ]
