# Generated by Django 5.2.10 on 2026-02-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0021_webinar_waba_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinarregistration',
            name='wants_reminder',
            field=models.BooleanField(default=True),
        ),
    ]
