# Generated by Django 5.2.11 on 2026-02-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0023_alter_webinar_is_registration_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='is_registration_open',
            field=models.BooleanField(default=True),
        ),
    ]
