# Generated by Django 5.2.11 on 2026-02-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0024_alter_webinar_is_registration_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='seats_available',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
