# Generated by Django 5.2.11 on 2026-02-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0242_alter_certificate_certificate_file'),
        ('webinar', '0025_webinar_seats_available'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='webinarregistration',
            index=models.Index(fields=['-registered_at'], name='webinar_web_registe_3cfe76_idx'),
        ),
        migrations.AddIndex(
            model_name='webinarregistration',
            index=models.Index(fields=['webinar'], name='webinar_web_webinar_aea1cf_idx'),
        ),
    ]
