# Generated by Django 5.2.11 on 2026-03-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0027_form_question_questionoption_submission_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='form',
            name='slug',
            field=models.SlugField(default='aryu-user', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
