# Generated by Django 5.2.11 on 2026-03-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0028_form_is_deleted_form_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='form_image',
            field=models.ImageField(blank=True, null=True, upload_to='form_images/'),
        ),
    ]
