# Generated by Django 5.2.11 on 2026-03-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0029_form_form_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
