# Generated by Django 5.2.11 on 2026-03-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0030_submission_is_deleted'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='webinarattendancelog',
            index=models.Index(fields=['-registration'], name='webinar_web_registr_02fd57_idx'),
        ),
    ]
