# Generated by Django 5.2.11 on 2026-03-20 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('webinar', '0031_webinarattendancelog_webinar_web_registr_02fd57_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinarregistration',
            name='payment_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymenttransaction'),
        ),
    ]
