# Generated by Django 5.2.11 on 2026-05-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0032_alter_webinarregistration_payment_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinarfeedback',
            name='phone',
            field=models.CharField(default='91', max_length=15),
        ),
    ]
