# Generated by Django 6.0.4 on 2026-05-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0033_alter_webinarfeedback_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinarregistration',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
