# Generated by Django 6.0.6 on 2026-06-06 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0034_alter_webinarregistration_source'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='webinarregistration',
            unique_together=set(),
        ),
    ]
