# Generated by Django 5.2.11 on 2026-06-09 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
        ('webinar', '0035_alter_webinarregistration_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinarregistration',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webinar_registrations', to='lead.lead'),
        ),
    ]
