# Generated by Django 6.0.4 on 2026-07-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0036_alter_webinarregistration_lead'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='webinarregistration',
            unique_together={('webinar', 'phone')},
        ),
        migrations.AddField(
            model_name='webinar',
            name='testimonial_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webinar',
            name='type',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='webinarregistration',
            name='student_type',
            field=models.CharField(default=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='webinarfeedback',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='webinarregistration',
            name='source',
            field=models.CharField(default='webinar', max_length=100),
        ),
        migrations.AddIndex(
            model_name='webinarfeedback',
            index=models.Index(fields=['webinar'], name='webinar_fee_webinar_7133a7_idx'),
        ),
        migrations.AddIndex(
            model_name='webinarfeedback',
            index=models.Index(fields=['submitted_at'], name='webinar_fee_submitt_a8f1a7_idx'),
        ),
        migrations.AddIndex(
            model_name='webinarfeedback',
            index=models.Index(fields=['overall_rating'], name='webinar_fee_overall_6ace27_idx'),
        ),
        migrations.RemoveField(
            model_name='webinarregistration',
            name='city',
        ),
        migrations.RemoveField(
            model_name='webinarregistration',
            name='state',
        ),
    ]
