# Generated by Django 6.0.4 on 2026-07-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0037_alter_webinarregistration_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
