# Generated by Django 6.0.4 on 2026-07-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0038_alter_webinar_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
