# Generated by Django 6.0.4 on 2026-08-21 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_course_category'),
        ('webinar', '0039_alter_webinar_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webinars', to='courses.course'),
        ),
    ]
