# Generated by Django 6.0.4 on 2026-06-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='duration_days',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
