# Generated by Django 6.0.4 on 2026-06-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_subscription_duration_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
