# Generated by Django 6.0.4 on 2026-06-15 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_subscription_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenthistory',
            old_name='name',
            new_name='plan_name',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='date',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='plan',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='payment_status',
            field=models.CharField(default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='payment_histories', to='resume.resumeregistration'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
