# Generated by Django 6.0.4 on 2026-08-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_subscription_ats_scan_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeregistration',
            name='email_verification_token',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resumeregistration',
            name='email_verification_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='resumeregistration',
            index=models.Index(fields=['email_verification_token'], name='resume_resu_email_v_eeeaa2_idx'),
        ),
    ]
