# Generated by Django 6.0.6 on 2026-08-10 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_resumeregistration_email_verification_token_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='resumeregistration',
            name='resume_resu_email_v_eeeaa2_idx',
        ),
        migrations.RemoveField(
            model_name='resumeregistration',
            name='email_verification_token',
        ),
        migrations.RemoveField(
            model_name='resumeregistration',
            name='email_verification_token_expiry',
        ),
    ]
