# Generated by Django 5.2.11 on 2026-09-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_remove_resumeregistration_resume_resu_email_v_eeeaa2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeregistration',
            name='google_sub',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
