# Generated by Django 5.2.11 on 2026-09-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_resumeregistration_google_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeregistration',
            name='auth_provider',
            field=models.CharField(default='email', help_text="Primary provider used during user registration (e.g., 'email', 'google')", max_length=50),
        ),
        migrations.AddField(
            model_name='resumeregistration',
            name='picture_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='resumeregistration',
            name='email',
            field=models.EmailField(db_index=True, default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resumeregistration',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='resumeregistration',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddIndex(
            model_name='resumeregistration',
            index=models.Index(fields=['google_sub'], name='resume_resu_google__a401c0_idx'),
        ),
    ]
