# Generated by Django 5.2.11 on 2026-09-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_resumeregistration_auth_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeregistration',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
    ]
