# Generated by Django 5.2.11 on 2026-09-16 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_alter_resumeregistration_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(db_index=True, max_length=100)),
                ('provider', models.CharField(default='gemini', max_length=50)),
                ('model', models.CharField(db_index=True, max_length=150)),
                ('request_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('cached_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(db_index=True, default='success', max_length=30)),
                ('error_message', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to='resume.resumeregistration')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='resume_aius_user_id_af6309_idx'), models.Index(fields=['operation', 'created_at'], name='resume_aius_operati_ec8374_idx'), models.Index(fields=['provider', 'model'], name='resume_aius_provide_5f56bf_idx'), models.Index(fields=['request_id'], name='resume_aius_request_fe3d69_idx'), models.Index(fields=['created_at'], name='resume_aius_created_435569_idx')],
            },
        ),
    ]
