# Generated by Django 5.2.11 on 2026-03-20 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_id'], name='aryuapp_cou_course__ba8ce1_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_name'], name='aryuapp_cou_course__73ae65_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['created_by', 'created_by_type'], name='aryuapp_cou_created_7819cd_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status', 'is_archived'], name='aryuapp_cou_status_c4c736_idx'),
        ),
    ]
