# Generated by Django 6.0.4 on 2026-04-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_aryuapp_cou_course__ba8ce1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration_type',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
