# Generated by Django 6.0.4 on 2026-07-14 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_student_syllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='scheduled_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='scheduled_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
