# Generated by Django 5.2.11 on 2026-08-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='syllabus_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='course/syllabus_thumbnails/'),
        ),
    ]
