# Generated by Django 5.2.11 on 2026-09-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_syllabus_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='syllabus_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
